spring.application.name=Smart Learning Assistant
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/smart_learning_assistant?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:root}
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
